spring.application.name=demo

spring.datasource.url=jdbc:sql://localhost:3306/assignment
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true